### ISSUE TITLE
Typo in readme?

### ISSUE THREAD

**Issue by amilbourne** [ianozsvald/dtype_diet#6]
In the Readme, under caveats, it says:

f16 is likely to be simulated on modern hardware so calculations will be 2-3* slower than on f32 or **f16**

Should this be:

f16 is likely to be simulated on modern hardware so calculations will be 2-3* slower than on f32 or **f64**

**Comment by ianozsvald** [comment]
Good spot :-) Fixed, cheers! I've added you to the README too, thanks.

**Comment by amilbourne** [comment]
Thanks for the contributor credit :-).
